"""conversation owner_id

Revision ID: 06576de47f6f
Revises: 7c7fccd168af
Create Date: 2024-10-07 13:59:29.661493

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06576de47f6f"
down_revision: str | None = "7c7fccd168af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.execute(
        """
        UPDATE conversation
        SET owner_id = link.user_id
        FROM userconversationlink link
        WHERE conversation.id = link.conversation_id;
        """
    )
    op.alter_column("conversation", "owner_id", nullable=False)
    op.create_foreign_key("conversation_owner_id_fkey", "conversation", "user", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("conversation_owner_id_fkey", "conversation", type_="foreignkey")
    op.drop_column("conversation", "owner_id")
    # ### end Alembic commands ###
