"""citation_in_conversation

Revision ID: 1ac06ea06d96
Revises: 941c40effa7c
Create Date: 2024-08-28 17:14:16.890042

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ac06ea06d96"
down_revision: str | None = "941c40effa7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation", sa.Column("citation_mode", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "citation_mode")
    # ### end Alembic commands ###
