"""llm profiles

Revision ID: 326c81bfa910
Revises: a542a2ff2e39
Create Date: 2024-09-20 11:24:27.510095

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "326c81bfa910"
down_revision: str | None = "a542a2ff2e39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", AutoString(length=128), nullable=False),
        sa.Column("provider", sa.Enum("LOCAL", "OPENAI", "BEDROCK", name="llmprovider"), nullable=False),
        sa.Column("llm_model_name", AutoString(), nullable=False),
        sa.Column("title_model_name", AutoString(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("title_temperature", sa.Float(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("top_p", sa.Float(), nullable=False),
        sa.Column("context_length", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("dbmessage", "llm")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dbmessage",
        sa.Column(
            "llm", postgresql.ENUM("LOCAL", "OPENAI", "BEDROCK", name="llmoptions"), autoincrement=False, nullable=False
        ),
    )
    op.drop_table("llm")
    # ### end Alembic commands ###
