"""remove URL from File

Revision ID: 4500f2e7c8f9
Revises: 326c81bfa910
Create Date: 2024-09-22 17:35:55.136451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4500f2e7c8f9"
down_revision: str | None = "326c81bfa910"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False, default="-"))
    # ### end Alembic commands ###
