"""expiration

Revision ID: 4f5db1227088
Revises: 4500f2e7c8f9
Create Date: 2024-09-24 13:05:25.707105

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f5db1227088"
down_revision: str | None = "4500f2e7c8f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fileuser", sa.Column("expiration_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fileuser", "expiration_time")
    # ### end Alembic commands ###
