"""bedrock

Revision ID: 5361409361fc
Revises: efbccf5b771d
Create Date: 2024-08-22 17:30:00.652602

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5361409361fc"
down_revision: str | None = "efbccf5b771d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE llmoptions ADD VALUE 'BEDROCK'")

    op.create_table(
        "spendinglimit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("INPUT_TOKEN", "OUTPUT_TOKEN", name="spendinglimittype"), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spendinglimit")
    # ### end Alembic commands ###
