"""directory_owner

Revision ID: 643689bde6e7
Revises: 5e97a0231c5e
Create Date: 2024-10-10 21:54:43.495292

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "643689bde6e7"
down_revision: str | None = "5e97a0231c5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("""
            INSERT INTO userdirectorylink (user_id, directory_id)
            SELECT owner_id, id FROM directory
            ON CONFLICT DO NOTHING;
            """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
