"""remove unused DBMessage.order field

Revision ID: 79a06bdf66cb
Revises: 876b8be16082
Create Date: 2024-10-01 12:35:51.069591

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79a06bdf66cb"
down_revision: str | None = "876b8be16082"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dbmessage", "order")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dbmessage", sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
