"""llm_aws_region

Revision ID: 7c7fccd168af
Revises: b1124d255c25
Create Date: 2024-10-01 13:12:10.353927

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "7c7fccd168af"
down_revision: str | None = "b1124d255c25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm", sa.Column("aws_region", AutoString(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm", "aws_region")
    # ### end Alembic commands ###
