"""update TitleIpdate model, change max_length value to 120

Revision ID: 876b8be16082
Revises: 707120461069
Create Date: 2024-10-01 13:13:12.773271

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "876b8be16082"
down_revision: str | None = "707120461069"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE conversation SET title = SUBSTRING(title, 1, 120)")
    op.alter_column(
        "conversation",
        "title",
        existing_type=sa.VARCHAR(length=300),
        type_=AutoString(length=120),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation",
        "title",
        existing_type=AutoString(length=120),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
