"""directory_default

Revision ID: a542a2ff2e39
Revises: 20618054f0a3
Create Date: 2024-09-19 14:44:29.774446

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a542a2ff2e39"
down_revision: str | None = "20618054f0a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE fileuser
        SET directory = '.'
        WHERE directory = '';
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE fileuser
        SET directory = ''
        WHERE directory = '.';
        """)
    # ### end Alembic commands ###
