"""homogenize timestamps

Revision ID: cb7fd7380dc3
Revises: fd1053375508
Create Date: 2024-09-24 11:52:15.730653

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb7fd7380dc3"
down_revision: str | None = "fd1053375508"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "adminsetting", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "chatbot", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "chatbot", sa.Column("modified", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "conversation", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "conversation",
        sa.Column("modified", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    )
    op.add_column(
        "dbmessage", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "dbmessage", sa.Column("modified", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "file", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "file", sa.Column("modified", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "fileuser", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "fileuser", sa.Column("modified", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column("fileuser", sa.Column("expires", sa.DateTime(), nullable=True))
    op.add_column(
        "group", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "group", sa.Column("modified", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "user", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "user", sa.Column("modified", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )

    op.execute("""
        UPDATE conversation SET created = ts_created, modified = ts_last_updated;
        UPDATE file SET created = creation_time;
        UPDATE fileuser SET created = creation_time, modified = modification_time, expires = expiration_time;
        UPDATE "group" SET created = creation_time;
        UPDATE "user" SET created = creation_time;
    """)

    op.drop_column("conversation", "ts_created")
    op.drop_column("conversation", "ts_last_updated")
    op.drop_column("file", "creation_time")
    op.drop_column("fileuser", "creation_time")
    op.drop_column("fileuser", "modification_time")
    op.drop_column("fileuser", "expiration_time")
    op.drop_column("group", "creation_time")
    op.drop_column("user", "creation_time")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("creation_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column("group", sa.Column("creation_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column("fileuser", sa.Column("creation_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column(
        "fileuser", sa.Column("modification_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.add_column("fileuser", sa.Column("expiration_time", sa.DateTime(), nullable=True))
    op.add_column("file", sa.Column("creation_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column(
        "conversation", sa.Column("ts_last_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.add_column("conversation", sa.Column("ts_created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.execute("""
        UPDATE conversation SET ts_created = created, ts_last_updated = modified;
        UPDATE file SET creation_time = created;
        UPDATE fileuser SET creation_time = created, modification_time = modified, expiration_time = expires;
        UPDATE "group" SET creation_time = created;
        UPDATE "user" SET creation_time = created;
    """)

    op.alter_column("group", "creation_time", nullable=False)
    op.alter_column("file", "creation_time", nullable=False)
    op.alter_column("conversation", "ts_last_updated", nullable=False)
    op.alter_column("conversation", "ts_created", nullable=False)

    op.drop_column("user", "modified")
    op.drop_column("user", "created")
    op.drop_column("group", "modified")
    op.drop_column("group", "created")
    op.drop_column("fileuser", "modified")
    op.drop_column("fileuser", "created")
    op.drop_column("fileuser", "expires")
    op.drop_column("file", "modified")
    op.drop_column("file", "created")
    op.drop_column("dbmessage", "modified")
    op.drop_column("dbmessage", "created")
    op.drop_column("conversation", "modified")
    op.drop_column("conversation", "created")
    op.drop_column("chatbot", "modified")
    op.drop_column("chatbot", "created")
    op.drop_column("adminsetting", "created")
    # ### end Alembic commands ###
