"""no_chatbot_name_constraint

Revision ID: ce71d72138c7
Revises: 79a06bdf66cb
Create Date: 2024-10-02 11:18:21.149191

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce71d72138c7"
down_revision: str | None = "79a06bdf66cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_user_chatbot_name_uc", "chatbot", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("_user_chatbot_name_uc", "chatbot", ["owner_id", "name"])
    # ### end Alembic commands ###
