"""fix_root_directory

Revision ID: d6926a070eeb
Revises: e52e6d6a9268
Create Date: 2024-10-08 20:49:25.407832

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6926a070eeb"
down_revision: str | None = "e52e6d6a9268"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_directory_owner_id"), "directory", ["owner_id"], unique=False)
    op.create_table(
        "userdirectorylink",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("directory_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["directory_id"], ["directory.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("user_id", "directory_id"),
    )
    op.create_unique_constraint(None, "userdirectorylink", ["directory_id"])
    op.execute(
        sa.text("""
            INSERT INTO userdirectorylink (user_id, directory_id)
            SELECT owner_id, id
            FROM directory
            """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userdirectorylink")
    op.drop_index(op.f("ix_directory_owner_id"), table_name="directory")
    # ### end Alembic commands ###
