"""reliable indexing

Revision ID: d88117952f5f
Revises: 1ac06ea06d96
Create Date: 2024-08-26 11:17:39.859037

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "d88117952f5f"
down_revision: str | None = "1ac06ea06d96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE indexingstatus AS ENUM ('PENDING', 'INDEXED', 'FAILED');")
    op.add_column(
        "file",
        sa.Column(
            "indexing_status",
            sa.Enum("PENDING", "INDEXED", "FAILED", name="indexingstatus"),
            nullable=False,
            server_default="PENDING",
        ),
    )
    op.execute("UPDATE file SET indexing_status = 'INDEXED' WHERE indexed = true;")
    op.create_index(op.f("ix_file_indexing_status"), "file", ["indexing_status"], unique=False)
    op.drop_column("file", "indexed")
    op.add_column("file", sa.Column("indexing_error", AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("indexed", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_file_indexing_status"), table_name="file")
    op.drop_column("file", "indexing_status")
    op.drop_column("file", "indexing_error")
    # ### end Alembic commands ###
