"""group_name_constraint

Revision ID: e52e6d6a9268
Revises: 06576de47f6f
Create Date: 2024-10-08 13:15:14.222693

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e52e6d6a9268"
down_revision: str | None = "06576de47f6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE "group" SET name = 'Name' WHERE name = '';
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
