"""email

Revision ID: fc0cb08a4a51
Revises: d88117952f5f
Create Date: 2024-08-30 21:16:23.389679

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "fc0cb08a4a51"
down_revision: str | None = "d88117952f5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", AutoString(), nullable=True))
    op.execute("UPDATE \"user\" SET email = username || '@skillbyte.de';")
    op.alter_column("user", "email", nullable=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
